# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_auto_20181124_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
